language: java

sudo: required

matrix:
  include:
    - language: java
      os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew outdated xctool || brew upgrade xctool
        - xcrun simctl list -j devices
        - npm install -g appium@1.7.2
      script:
      - Platform="ios" mvn clean -Dtest=Runner test
    - language: android
      os: linux
      jdk: oraclejdk8
      android:
        components:
          - build-tools-26.0.2
          - platform-tools
          - tools
          - android-22
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-22
      before_install:
        # node stuff
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
        - nvm install 6
        - node --version
        - npm --version
        - npm install -g appium@1.7.2
        - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb devices
        - appium -v
      script:
      - Platform="android" mvn clean -Dtest=Runner test
